image: node:10.15.3

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - npm install
          - npm audit fix
          - npm test
  branches:
    dev:
      - step:
          script:
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git dev:master

    master:
      - step:
          script:
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$PROD_HEROKU_APP_NAME.git
